[package]
name = "blst_ringct"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1"
tiny-keccak = { version = "2.0", features = ["sha3"] }
bulletproofs = { git = "https://github.com/maidsafe/blst-bulletproofs.git"}
serde = { version = "1.0.130", optional = true }

[dev-dependencies]
quickcheck = "1"
quickcheck_macros = "1"
